// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwZYhZ7EF1NO5hKtm0jWoDqsF_QO11L3k',
    appId: '1:270143030213:web:8b71fab58630bc12efc1ac',
    messagingSenderId: '270143030213',
    projectId: 'cancer-cell-analysis',
    authDomain: 'cancer-cell-analysis.firebaseapp.com',
    storageBucket: 'cancer-cell-analysis.firebasestorage.app',
    measurementId: 'G-G795VM9BC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYznu9z1a-mggX9yoUvG5PXn6EWttPcDI',
    appId: '1:270143030213:android:57c5be9c451ef595efc1ac',
    messagingSenderId: '270143030213',
    projectId: 'cancer-cell-analysis',
    storageBucket: 'cancer-cell-analysis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrqSd1Z4Votpv_4fQTVQo33mR0b1VQTUA',
    appId: '1:270143030213:ios:62ecc7be232b4502efc1ac',
    messagingSenderId: '270143030213',
    projectId: 'cancer-cell-analysis',
    storageBucket: 'cancer-cell-analysis.firebasestorage.app',
    iosClientId: '270143030213-c2cecutf8eqkep3dag10n3tribr43on5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancerCellAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrqSd1Z4Votpv_4fQTVQo33mR0b1VQTUA',
    appId: '1:270143030213:ios:62ecc7be232b4502efc1ac',
    messagingSenderId: '270143030213',
    projectId: 'cancer-cell-analysis',
    storageBucket: 'cancer-cell-analysis.firebasestorage.app',
    iosClientId: '270143030213-c2cecutf8eqkep3dag10n3tribr43on5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancerCellAnalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwZYhZ7EF1NO5hKtm0jWoDqsF_QO11L3k',
    appId: '1:270143030213:web:cbe909b113ff1c6defc1ac',
    messagingSenderId: '270143030213',
    projectId: 'cancer-cell-analysis',
    authDomain: 'cancer-cell-analysis.firebaseapp.com',
    storageBucket: 'cancer-cell-analysis.firebasestorage.app',
    measurementId: 'G-HYC7HD129B',
  );
}
